version: '3.8'

services:
  ftp:
    build:
      context: .
      args:
        HOST_UID: ${UID}
        HOST_GID: ${GID}
    image: custom-pure-ftpd
    container_name: ftp-server
    restart: unless-stopped
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    environment:
      PUBLICHOST: 127.0.0.1           # ← 改成你的內網或外網 IP
      FTP_USER_NAME: user
      FTP_USER_PASS: password
      FTP_USER_HOME: /home/ftpusers/user
      ADDED_FLAGS: "-d -E -j -X -P 127.0.0.1 -p 30000:30009"
    volumes:
      - /home/pudding/ramdisk:/home/ftpusers/user
